import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MAIN',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Admin Modules
  {
    path: '/manager/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_MANAGER'],
    submenu: [],
  },
  {
    path: '',
    title: 'Configurations',
    moduleName: 'meetings',
    iconType: 'feather',
    icon: 'slack',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_MANAGER'],
    submenu: [
      {
        path: '/manager/configurations/company',
        title: 'Company',
        moduleName: 'profile',
        iconType: 'feather',
        icon: 'layers',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_MANAGER'],
        submenu: [],
      },

      {
        path: '/manager/configurations/department',
        title: 'Departments',
        moduleName: 'profile',
        iconType: 'feather',
        icon: 'layers',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_MANAGER'],
        submenu: [],
      },
      {
        path: '/manager/configurations/vendor',
        title: 'Vendor',
        moduleName: 'profile',
        iconType: 'feather',
        icon: 'layers',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_MANAGER'],
        submenu: [],
      },
      {
        path: '/manager/configurations/customer',
        title: 'Customer',
        moduleName: 'profile',
        iconType: 'feather',
        icon: 'layers',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_MANAGER'],
        submenu: [],
      },
      {
        path: '/manager/configurations/product',
        title: 'Products',
        moduleName: 'profile',
        iconType: 'feather',
        icon: 'layers',
        class: '',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['ROLE_MANAGER'],
        submenu: [],
      },      
    ],
  },

  {
    path: '/manager/purchases/main',
    title: 'Ordering',
    moduleName: 'ordering',
    iconType: 'feather',
    icon: 'box',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_MANAGER'],
    submenu: [],
  },

  {
    path: '/manager/purchases/main',
    title: 'Purchases',
    moduleName: 'purchases',
    iconType: 'feather',
    icon: 'shopping-cart',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_MANAGER'],
    submenu: [],
  },


  {
    path: '',
    title: 'Roles',
    moduleName: 'RolesModule',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_MANAGER'],
    submenu: [
      {
        path: '/manager/roles/add',
        title: 'Add Role',
        moduleName: 'RolesModule',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

      {
        path: '/manager/roles/view',
        title: 'View Role',
        moduleName: 'RolesModule',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'User Accounts',
    moduleName: 'user-accounts',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_MANAGER'],
    submenu: [
      {
        path: '/manager/user-accounts/add-account',
        title: 'Add Account',
        moduleName: 'add-account',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/manager/user-accounts/all',
        title: 'All Accounts',
        moduleName: 'active-accounts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/manager/user-accounts/locked-accounts',
        title: 'Locked Accounts',
        moduleName: 'locked-accounts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/manager/user-accounts/deleted-accounts',
        title: 'Deleted Accounts',
        moduleName: 'deleted-accounts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },


  // dealer Modules
  
  
  {
    path: '/dealer/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },

  {
    path: '/dealer/branches/main',
    title: 'Branches',
    moduleName: 'branches',
    iconType: 'feather',
    icon: 'share-2',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },
  
  {
    path: '',
    title: 'User Accounts',
    moduleName: 'user-accounts',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/dealer/user-accounts/branch-managers',
        title: 'Branch Managers',
        moduleName: 'add-account',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

      {
        path: '/dealer/user-accounts/users',
        title: 'All Users',
        moduleName: 'all Users',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ]
  },

  {
    path: '/dealer/user-roles/roles',
    title: 'Roles',
    moduleName: 'role-management',
    iconType: 'feather',
    icon: 'book',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },
      
  

];
