import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: 'MAIN',
    moduleName: '',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    role: ['All'],
    submenu: [],
  },

  // Admin Modules
  {
    path: '/admin/dashboard/main',
    title: 'Dashboard',
    moduleName: 'dashboard',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [],
  },
  // {
  //   path: '/manager/sales/totals-collections',
  //   title: 'Totals Collections',
  //   moduleName: 'sales',
  //   iconType: 'feather',
  //   icon: 'layers',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['ROLE_ADMIN'],
  //   submenu: [],
  // },
  // {
  //   path: '/admin/payments/records',
  //   title: 'Payment Records',
  //   moduleName: 'payments',
  //   iconType: 'feather',
  //   icon: 'shopping-cart',
  //   class: '',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['ROLE_ADMIN'],
  //   submenu: [],
  // },
  
  // {
  //   path: '',
  //   title: 'Configurations',
  //   moduleName: 'meetings',
  //   iconType: 'feather',
  //   icon: 'slack',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['ROLE_ADMIN'],
  //   submenu: [
  //     {
  //       path: '/admin/business-profile/create',
  //       title: 'Business Profile',
  //       moduleName: 'profile',
  //       iconType: 'feather',
  //       icon: 'layers',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: ['ROLE_ADMIN'],
  //       submenu: [],
  //     },
  //     {
  //       path: '/admin/price-config',
  //       title: 'Price Configurations',
  //       moduleName: 'users',
  //       iconType: 'feather',
  //       icon: 'layers',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: ['ROLE_ADMIN'],
  //       submenu: []
  //     },
  //     {
  //       path: "/admin/pickup-locations",
  //       title: "Routes",
  //       moduleName: "pickup",
  //       iconType: "feather",
  //       icon: "layers",
  //       class: "",
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: ['ROLE_ADMIN'],
  //       submenu: [],
  //     },
  //     {
  //       path: '/admin/farmers/farmers',
  //       title: 'Farmers',
  //       moduleName: 'farmers',
  //       iconType: 'feather',
  //       icon: 'cloud-rain',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: ['ROLE_ADMIN'],
  //       submenu: [],
  //     },
  //     {
  //       path: '/admin/accountant/customers',
  //       title: 'Customers',
  //       moduleName: 'customers',
  //       iconType: 'feather',
  //       icon: 'divide',
  //       class: '',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       role: ['ACCOUNTANT'],
  //       submenu: [],
  //     },
  //   ],
  // },


  {
    path: '',
    title: 'Roles',
    moduleName: 'RolesModule',
    iconType: 'feather',
    icon: 'book',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/admin/roles/add',
        title: 'Add Role',
        moduleName: 'RolesModule',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },

      {
        path: '/admin/roles/view',
        title: 'View Role',
        moduleName: 'RolesModule',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },
  {
    path: '',
    title: 'User Accounts',
    moduleName: 'user-accounts',
    iconType: 'feather',
    icon: 'user',
    class: 'menu-toggle',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['ROLE_ADMIN'],
    submenu: [
      {
        path: '/admin/user-accounts/add-account',
        title: 'Add Account',
        moduleName: 'add-account',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/user-accounts/all',
        title: 'All Accounts',
        moduleName: 'active-accounts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/user-accounts/locked-accounts',
        title: 'Locked Accounts',
        moduleName: 'locked-accounts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
      {
        path: '/admin/user-accounts/deleted-accounts',
        title: 'Deleted Accounts',
        moduleName: 'deleted-accounts',
        iconType: '',
        icon: '',
        class: 'ml-menu',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: [''],
        submenu: [],
      },
    ],
  },

  
];
